2025-03-27 09:40:59 CST [1]: [3-1] user=,db=,app=,client= LOG:  starting PostgreSQL 15.12 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
2025-03-27 09:40:59 CST [1]: [4-1] user=,db=,app=,client= LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-03-27 09:40:59 CST [1]: [5-1] user=,db=,app=,client= LOG:  listening on IPv6 address "::", port 5432
2025-03-27 09:41:01 CST [1]: [6-1] user=,db=,app=,client= LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-03-27 09:41:02 CST [30]: [1-1] user=,db=,app=,client= LOG:  database system was interrupted; last known up at 2025-03-26 21:29:31 CST
2025-03-27 09:41:13 CST [30]: [2-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 10.52 s, current path: ./base/1/2601_fsm
2025-03-27 09:41:23 CST [30]: [3-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 20.19 s, current path: ./base/1/2610_vm
2025-03-27 09:41:33 CST [30]: [4-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 30.05 s, current path: ./base/1/2669
2025-03-27 09:41:43 CST [30]: [5-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 40.09 s, current path: ./base/1/3502
2025-03-27 09:41:53 CST [30]: [6-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 50.01 s, current path: ./base/16384/2600
2025-03-27 09:42:03 CST [30]: [7-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 60.02 s, current path: ./base/16384/3767
2025-03-27 09:42:13 CST [30]: [8-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 70.03 s, current path: ./base/4/2664
2025-03-27 09:42:23 CST [30]: [9-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 80.03 s, current path: ./base/5/1255_vm
2025-03-27 09:42:33 CST [30]: [10-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 90.03 s, current path: ./base/5/2691
2025-03-27 09:42:43 CST [30]: [11-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 100.00 s, current path: ./global/2695
2025-03-27 09:42:53 CST [30]: [12-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 110.15 s, current path: ./log/postgresql-2025-03-14_193457.log
2025-03-27 09:42:58 CST [30]: [13-1] user=,db=,app=,client= LOG:  database system was not properly shut down; automatic recovery in progress
2025-03-27 09:42:58 CST [30]: [14-1] user=,db=,app=,client= LOG:  redo starts at 0/197E1A8
2025-03-27 09:42:58 CST [30]: [15-1] user=,db=,app=,client= LOG:  invalid record length at 0/197E290: wanted 24, got 0
2025-03-27 09:42:58 CST [30]: [16-1] user=,db=,app=,client= LOG:  redo done at 0/197E258 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.10 s
2025-03-27 09:42:59 CST [28]: [1-1] user=,db=,app=,client= LOG:  checkpoint starting: end-of-recovery immediate wait
2025-03-27 09:43:01 CST [28]: [2-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.519 s, sync=0.269 s, total=2.158 s; sync files=2, longest=0.146 s, average=0.135 s; distance=0 kB, estimate=0 kB
2025-03-27 09:43:02 CST [1]: [7-1] user=,db=,app=,client= LOG:  database system is ready to accept connections
