2025-03-11 10:40:05 CST [1]: [3-1] user=,db=,app=,client= LOG:  starting PostgreSQL 15.12 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
2025-03-11 10:40:05 CST [1]: [4-1] user=,db=,app=,client= LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-03-11 10:40:05 CST [1]: [5-1] user=,db=,app=,client= LOG:  listening on IPv6 address "::", port 5432
2025-03-11 10:40:06 CST [1]: [6-1] user=,db=,app=,client= LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-03-11 10:40:07 CST [30]: [1-1] user=,db=,app=,client= LOG:  database system was interrupted; last known up at 2025-03-11 09:53:55 CST
2025-03-11 10:40:18 CST [30]: [2-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 10.24 s, current path: ./base/1/2602_fsm
2025-03-11 10:40:28 CST [30]: [3-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 20.01 s, current path: ./base/1/6176
2025-03-11 10:40:38 CST [30]: [4-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 30.03 s, current path: ./base/4/2224
2025-03-11 10:40:48 CST [30]: [5-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 40.08 s, current path: ./base/4/2838_vm
2025-03-11 10:40:59 CST [30]: [6-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 50.54 s, current path: ./base/5/1255_vm
2025-03-11 10:41:08 CST [30]: [7-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 60.00 s, current path: ./base/5/2654
2025-03-11 10:41:18 CST [30]: [8-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 70.01 s, current path: ./base/5/4155
2025-03-11 10:41:26 CST [30]: [9-1] user=,db=,app=,client= LOG:  database system was not properly shut down; automatic recovery in progress
2025-03-11 10:41:26 CST [30]: [10-1] user=,db=,app=,client= LOG:  redo starts at 0/197B288
2025-03-11 10:41:26 CST [30]: [11-1] user=,db=,app=,client= LOG:  invalid record length at 0/197B370: wanted 24, got 0
2025-03-11 10:41:26 CST [30]: [12-1] user=,db=,app=,client= LOG:  redo done at 0/197B338 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.01 s
2025-03-11 10:41:26 CST [28]: [1-1] user=,db=,app=,client= LOG:  checkpoint starting: end-of-recovery immediate wait
2025-03-11 10:41:27 CST [28]: [2-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.181 s, sync=0.124 s, total=0.859 s; sync files=2, longest=0.074 s, average=0.062 s; distance=0 kB, estimate=0 kB
2025-03-11 10:41:27 CST [1]: [7-1] user=,db=,app=,client= LOG:  database system is ready to accept connections
2025-03-11 12:45:41 CST [1]: [8-1] user=,db=,app=,client= LOG:  received fast shutdown request
2025-03-11 12:45:42 CST [1]: [9-1] user=,db=,app=,client= LOG:  aborting any active transactions
2025-03-11 12:45:42 CST [1]: [10-1] user=,db=,app=,client= LOG:  background worker "logical replication launcher" (PID 33) exited with exit code 1
2025-03-11 12:45:42 CST [28]: [3-1] user=,db=,app=,client= LOG:  shutting down
2025-03-11 12:45:42 CST [28]: [4-1] user=,db=,app=,client= LOG:  checkpoint starting: shutdown immediate
2025-03-11 12:45:43 CST [28]: [5-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.224 s, sync=0.001 s, total=1.213 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=0 kB
2025-03-11 12:45:43 CST [1]: [11-1] user=,db=,app=,client= LOG:  database system is shut down
