2025-03-24 15:44:41 CST [1]: [3-1] user=,db=,app=,client= LOG:  starting PostgreSQL 15.12 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
2025-03-24 15:44:41 CST [1]: [4-1] user=,db=,app=,client= LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-03-24 15:44:41 CST [1]: [5-1] user=,db=,app=,client= LOG:  listening on IPv6 address "::", port 5432
2025-03-24 15:44:42 CST [1]: [6-1] user=,db=,app=,client= LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-03-24 15:44:43 CST [30]: [1-1] user=,db=,app=,client= LOG:  database system was interrupted; last known up at 2025-03-24 11:08:03 CST
2025-03-24 15:44:54 CST [30]: [2-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 10.01 s, current path: ./base/1/2615
2025-03-24 15:45:04 CST [30]: [3-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 20.02 s, current path: ./base/1/2836_fsm
2025-03-24 15:45:14 CST [30]: [4-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 30.02 s, current path: ./base/1/3764_vm
2025-03-24 15:45:24 CST [30]: [5-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 40.17 s, current path: ./base/16384/1417
2025-03-24 15:45:34 CST [30]: [6-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 50.02 s, current path: ./base/16384/2689
2025-03-24 15:45:44 CST [30]: [7-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 60.05 s, current path: ./base/16384/3605
2025-03-24 15:45:54 CST [30]: [8-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 70.08 s, current path: ./base/4/175
2025-03-24 15:46:04 CST [30]: [9-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 80.00 s, current path: ./base/4/6113
2025-03-24 15:46:14 CST [30]: [10-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 90.01 s, current path: ./base/5/548
2025-03-24 15:46:18 CST [30]: [11-1] user=,db=,app=,client= LOG:  database system was not properly shut down; automatic recovery in progress
2025-03-24 15:46:18 CST [30]: [12-1] user=,db=,app=,client= LOG:  redo starts at 0/197D6D8
2025-03-24 15:46:18 CST [30]: [13-1] user=,db=,app=,client= LOG:  invalid record length at 0/197D7C0: wanted 24, got 0
2025-03-24 15:46:18 CST [30]: [14-1] user=,db=,app=,client= LOG:  redo done at 0/197D788 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.06 s
2025-03-24 15:46:19 CST [28]: [1-1] user=,db=,app=,client= LOG:  checkpoint starting: end-of-recovery immediate wait
2025-03-24 15:46:20 CST [28]: [2-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.281 s, sync=0.152 s, total=1.714 s; sync files=2, longest=0.106 s, average=0.076 s; distance=0 kB, estimate=0 kB
2025-03-24 15:46:21 CST [1]: [7-1] user=,db=,app=,client= LOG:  database system is ready to accept connections
