2025-03-21 14:24:41 CST [1]: [3-1] user=,db=,app=,client= LOG:  starting PostgreSQL 15.12 on x86_64-pc-linux-musl, compiled by gcc (Alpine 14.2.0) 14.2.0, 64-bit
2025-03-21 14:24:41 CST [1]: [4-1] user=,db=,app=,client= LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-03-21 14:24:41 CST [1]: [5-1] user=,db=,app=,client= LOG:  listening on IPv6 address "::", port 5432
2025-03-21 14:24:42 CST [1]: [6-1] user=,db=,app=,client= LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-03-21 14:24:42 CST [30]: [1-1] user=,db=,app=,client= LOG:  database system was interrupted; last known up at 2025-03-21 10:25:39 CST
2025-03-21 14:24:53 CST [30]: [2-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 10.10 s, current path: ./base/1/2608_fsm
2025-03-21 14:25:03 CST [30]: [3-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 20.03 s, current path: ./base/1/3602_fsm
2025-03-21 14:25:13 CST [30]: [4-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 30.02 s, current path: ./base/16384/3394_vm
2025-03-21 14:25:23 CST [30]: [5-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 40.01 s, current path: ./base/4/2835
2025-03-21 14:25:33 CST [30]: [6-1] user=,db=,app=,client= LOG:  syncing data directory (fsync), elapsed time: 50.00 s, current path: ./base/5/2670
2025-03-21 14:25:42 CST [30]: [7-1] user=,db=,app=,client= LOG:  database system was not properly shut down; automatic recovery in progress
2025-03-21 14:25:42 CST [30]: [8-1] user=,db=,app=,client= LOG:  redo starts at 0/197CB00
2025-03-21 14:25:42 CST [30]: [9-1] user=,db=,app=,client= LOG:  invalid record length at 0/197CB38: wanted 24, got 0
2025-03-21 14:25:42 CST [30]: [10-1] user=,db=,app=,client= LOG:  redo done at 0/197CB00 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.18 s
2025-03-21 14:25:44 CST [28]: [1-1] user=,db=,app=,client= LOG:  checkpoint starting: end-of-recovery immediate wait
2025-03-21 14:25:47 CST [28]: [2-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.749 s, sync=0.246 s, total=3.413 s; sync files=2, longest=0.141 s, average=0.123 s; distance=0 kB, estimate=0 kB
2025-03-21 14:25:48 CST [1]: [7-1] user=,db=,app=,client= LOG:  database system is ready to accept connections
2025-03-21 16:04:30 CST [1]: [8-1] user=,db=,app=,client= LOG:  received fast shutdown request
2025-03-21 16:04:31 CST [1]: [9-1] user=,db=,app=,client= LOG:  aborting any active transactions
2025-03-21 16:04:31 CST [1]: [10-1] user=,db=,app=,client= LOG:  background worker "logical replication launcher" (PID 33) exited with exit code 1
2025-03-21 16:04:31 CST [28]: [3-1] user=,db=,app=,client= LOG:  shutting down
2025-03-21 16:04:31 CST [28]: [4-1] user=,db=,app=,client= LOG:  checkpoint starting: shutdown immediate
2025-03-21 16:04:32 CST [28]: [5-1] user=,db=,app=,client= LOG:  checkpoint complete: wrote 0 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.325 s, sync=0.001 s, total=1.676 s; sync files=0, longest=0.000 s, average=0.000 s; distance=0 kB, estimate=0 kB
2025-03-21 16:04:32 CST [1]: [11-1] user=,db=,app=,client= LOG:  database system is shut down
